# Generated by Django 5.1.8 on 2025-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0006_add_primary_identifier_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='primary_identifier',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
    ]
