# Generated by Django 5.1.6 on 2025-04-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0007_make_primary_identifier_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='primary_identifier',
        ),
    ]
