# Generated by Django 5.1.6 on 2025-04-29 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0008_remove_item_primary_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 29, 23, 13, 9, 969207, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
